// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Dominio.JugadorFemenino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NivelHabilidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoDeReaccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JugadoresFemeninos", (string)null);
                });

            modelBuilder.Entity("Data.Dominio.JugadorMasculino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fuerza")
                        .HasColumnType("int");

                    b.Property<int>("NivelHabilidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Velocidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JugadoresMasculinos", (string)null);
                });

            modelBuilder.Entity("Data.Dominio.PartidoFemenino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IPartidoSiguiente")
                        .HasColumnType("int");

                    b.Property<int?>("IdGanador")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador1")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador2")
                        .HasColumnType("int");

                    b.Property<int?>("IdTorneo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IPartidoSiguiente");

                    b.HasIndex("IdGanador");

                    b.HasIndex("IdJugador1");

                    b.HasIndex("IdJugador2");

                    b.HasIndex("IdTorneo");

                    b.ToTable("PartidosFemeninos", (string)null);
                });

            modelBuilder.Entity("Data.Dominio.PartidoMasculino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IPartidoSiguiente")
                        .HasColumnType("int");

                    b.Property<int?>("IdGanador")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador1")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador2")
                        .HasColumnType("int");

                    b.Property<int?>("IdTorneo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IPartidoSiguiente");

                    b.HasIndex("IdGanador");

                    b.HasIndex("IdJugador1");

                    b.HasIndex("IdJugador2");

                    b.HasIndex("IdTorneo");

                    b.ToTable("PartidosMasculinos", (string)null);
                });

            modelBuilder.Entity("Data.Dominio.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Torneos", (string)null);
                });

            modelBuilder.Entity("Data.Dominio.PartidoFemenino", b =>
                {
                    b.HasOne("Data.Dominio.PartidoFemenino", "PartidoSiguiente")
                        .WithMany()
                        .HasForeignKey("IPartidoSiguiente");

                    b.HasOne("Data.Dominio.JugadorFemenino", "Ganador")
                        .WithMany()
                        .HasForeignKey("IdGanador");

                    b.HasOne("Data.Dominio.JugadorFemenino", "Jugador1")
                        .WithMany()
                        .HasForeignKey("IdJugador1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Dominio.JugadorFemenino", "Jugador2")
                        .WithMany()
                        .HasForeignKey("IdJugador2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Dominio.Torneo", "Torneo")
                        .WithMany("PartidosFemeninos")
                        .HasForeignKey("IdTorneo");

                    b.Navigation("Ganador");

                    b.Navigation("Jugador1");

                    b.Navigation("Jugador2");

                    b.Navigation("PartidoSiguiente");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Data.Dominio.PartidoMasculino", b =>
                {
                    b.HasOne("Data.Dominio.PartidoMasculino", "PartidoSiguiente")
                        .WithMany()
                        .HasForeignKey("IPartidoSiguiente");

                    b.HasOne("Data.Dominio.JugadorMasculino", "Ganador")
                        .WithMany()
                        .HasForeignKey("IdGanador");

                    b.HasOne("Data.Dominio.JugadorMasculino", "Jugador1")
                        .WithMany()
                        .HasForeignKey("IdJugador1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Dominio.JugadorMasculino", "Jugador2")
                        .WithMany()
                        .HasForeignKey("IdJugador2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Dominio.Torneo", "Torneo")
                        .WithMany("PartidosMasculinos")
                        .HasForeignKey("IdTorneo");

                    b.Navigation("Ganador");

                    b.Navigation("Jugador1");

                    b.Navigation("Jugador2");

                    b.Navigation("PartidoSiguiente");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Data.Dominio.Torneo", b =>
                {
                    b.Navigation("PartidosFemeninos");

                    b.Navigation("PartidosMasculinos");
                });
#pragma warning restore 612, 618
        }
    }
}
